include fastcgi_params;
fastcgi_param HTTP_TRACEPARENT "";
fastcgi_param HTTP_TRACESTATE "";
fastcgi_param HTTP_X_REQUEST_ID $effective_request_id;
fastcgi_pass backend_upstream;
fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
fastcgi_param DOCUMENT_ROOT /var/www/html/public;
fastcgi_param QUERY_STRING $query_string;
fastcgi_param REQUEST_METHOD $request_method;
fastcgi_param HTTPS on;
